### ISSUE TITLE
Typescript example

### ISSUE THREAD

**Issue by sapter** [rperon/epic-stack-with-i18n#3]
Very nice demo so far. Would be nice to add type safety to the `t` function per https://www.i18next.com/overview/typescript

**Comment by rperon** [comment]
Hello @sapter, I updated the example and added a `i18next.d.ts` files with types. :)

Is this what you were looking for ?

**Comment by sapter** [comment]
Yes, @rperon. Thank you; much appreciated. 
Closing.
