### ISSUE TITLE
Hydration issue when trying to add a new string

### ISSUE THREAD

**Issue by voieducode** [rperon/epic-stack-with-i18n#5]
Hi there,

Thanks for the example, I have followed it, but I get some strange behaviour. I might be doing something wrong, so I wanted to double check with you.

I have applied the following changes to my local repo:

```
diff --git a/app/routes/_marketing+/index.tsx b/app/routes/_marketing+/index.tsx
index de256fd..658b663 100644
--- a/app/routes/_marketing+/index.tsx
+++ b/app/routes/_marketing+/index.tsx
@@ -69,6 +69,9 @@ export default function Index() {
 						</a>{' '}
 						{t('marketing.title.end')}
 					</p>
+					<p>
+					{t('root.morestuff')}
+					</p>
 				</div>
 				<ul className="mt-16 flex max-w-3xl flex-wrap justify-center gap-2 sm:gap-4 xl:mt-0 xl:grid xl:grid-flow-col xl:grid-cols-5 xl:grid-rows-6">
 					<TooltipProvider>
diff --git a/public/locales/en/common.json b/public/locales/en/common.json
index 8030530..8fb734b 100644
--- a/public/locales/en/common.json
+++ b/public/locales/en/common.json
@@ -10,5 +10,6 @@
   "root.profile": "Profile",
   "root.logout": "Logout",
   "root.notes": "Notes",
-  "search": "Search"
+  "search": "Search",
+  "root.morestuff": "More stuff"
 }
diff --git a/public/locales/fr/common.json b/public/locales/fr/common.json
index 3ee3745..966a92d 100644
--- a/public/locales/fr/common.json
+++ b/public/locales/fr/common.json
@@ -10,5 +10,6 @@
   "root.profile": "Profil",
   "root.logout": "Se déconnecter",
   "root.notes": "Notes",
-  "search": "Rechercher"
+  "search": "Rechercher",
+  "root.morestuff": "Plus de trucs"
 }

```
Then after refreshing the page, I get "root.morestuff" instead of the expected translated string. Here is what I get in the console:

> [Error] Warning: Text content did not match. Server: "More stuff" Client: "root.morestuff"
> p
> div
> div
> main
> Index@http://localhost:3000/build/routes/_marketing+/index-EXR5YWDN.js:294:21
> RenderedRoute@http://localhost:3000/build/_shared/chunk-ND4NONL7.js:3901:32
> Outlet@http://localhost:3000/build/_shared/chunk-ND4NONL7.js:4315:25
> div
> div
> body
> html
> Document@http://localhost:3000/build/root-IDDC63OD.js:3525:16
> App@http://localhost:3000/build/root-IDDC63OD.js:3598:29
> HoneypotProvider@http://localhost:3000/build/_shared/chunk-LVG5BNEL.js:28:15
> AppWithProviders@http://localhost:3000/build/root-IDDC63OD.js:3739:29
> SentryRoot
> RenderedRoute@http://localhost:3000/build/_shared/chunk-ND4NONL7.js:3901:32
> RenderErrorBoundary@http://localhost:3000/build/_shared/chunk-ND4NONL7.js:4544:14
> DataRoutes2@http://localhost:3000/build/_shared/chunk-ND4NONL7.js:5194:23
> Router@http://localhost:3000/build/_shared/chunk-ND4NONL7.js:4325:28
> RouterProvider2@http://localhost:3000/build/_shared/chunk-ND4NONL7.js:5007:20
> RemixErrorBoundary@http://localhost:3000/build/_shared/chunk-ND4NONL7.js:7194:10
> RemixBrowser@http://localhost:3000/build/_shared/chunk-ND4NONL7.js:8028:58
> I18nextProvider@http://localhost:3000/build/_shared/chunk-Z2OBV7NI.js:122:9
> 	printWarning (chunk-WEAPBHQG.js:521)
> 	error (chunk-WEAPBHQG.js:505)
> 	checkForUnmatchedText (chunk-WEAPBHQG.js:7410)
> 	diffHydratedProperties (chunk-WEAPBHQG.js:7869)
> 	prepareToHydrateHostInstance (chunk-WEAPBHQG.js:9528)
> 	completeWork (chunk-WEAPBHQG.js:16275)
> 	completeUnitOfWork (chunk-WEAPBHQG.js:19220)
> 	performUnitOfWork (chunk-WEAPBHQG.js:19202)
> 	workLoopConcurrent (chunk-WEAPBHQG.js:19185)
> 	renderRootConcurrent (chunk-WEAPBHQG.js:19160)
> 	performConcurrentWorkOnRoot (chunk-WEAPBHQG.js:18674)
> 	workLoop (chunk-WEAPBHQG.js:197)
> 	flushWork (chunk-WEAPBHQG.js:176)
> 	performWorkUntilDeadline (chunk-WEAPBHQG.js:384)
> 
> [Error] Error: Hydration failed because the initial UI does not match what was rendered on the server.
> throwOnHydrationMismatch — react-dom.development.js:12507
> tryToClaimNextHydratableInstance — react-dom.development.js:12520
> updateHostComponent — react-dom.development.js:19902
> beginWork$1 — react-dom.development.js:27426
> performUnitOfWork — react-dom.development.js:26557
> workLoopConcurrent — react-dom.development.js:26543
> renderRootConcurrent — react-dom.development.js:26505
> performConcurrentWorkOnRoot — react-dom.development.js:25738
> workLoop — scheduler.development.js:266
> flushWork — scheduler.development.js:239
> performWorkUntilDeadline — scheduler.development.js:533
> 
> 	RemixRootDefaultErrorBoundary (chunk-ND4NONL7.js:7230)
> 	renderWithHooks (chunk-WEAPBHQG.js:12171)
> 	mountIndeterminateComponent (chunk-WEAPBHQG.js:14921)
> 	beginWork$1 (chunk-WEAPBHQG.js:19749)
> 	performUnitOfWork (chunk-WEAPBHQG.js:19194)
> 	workLoopConcurrent (chunk-WEAPBHQG.js:19185)
> 	renderRootConcurrent (chunk-WEAPBHQG.js:19160)
> 	performConcurrentWorkOnRoot (chunk-WEAPBHQG.js:18674)
> 	workLoop (chunk-WEAPBHQG.js:197)
> 	flushWork (chunk-WEAPBHQG.js:176)
> 	performWorkUntilDeadline (chunk-WEAPBHQG.js:384)
> [...]
> [Error] Warning: An error occurred during hydration. The server HTML was replaced with client content in <#document>.
> 	printWarning (chunk-WEAPBHQG.js:521)
> 	error (chunk-WEAPBHQG.js:505)
> 	errorHydratingContainer (chunk-WEAPBHQG.js:8769)
> 	recoverFromConcurrentError (chunk-WEAPBHQG.js:18729)
> 	performConcurrentWorkOnRoot (chunk-WEAPBHQG.js:18680)
> 	workLoop (chunk-WEAPBHQG.js:197)
> 	flushWork (chunk-WEAPBHQG.js:176)
> 	performWorkUntilDeadline (chunk-WEAPBHQG.js:384)
> etc.

This continues to happen even after restarting the app. It happens in different browsers. Do you get the same problem?

Thanks
Dinh

**Comment by voieducode** [comment]
And I did try to revert to an old commit https://github.com/rperon/epic-stack-with-i18n/commit/a7ecc98c514b767acea0af3a963ca72a2ae715ba and I get the same problem.

And to be thorough, I tried doing something similar on https://github.com/locize/locize-remix-i18next-example/ and I get the same hydration error.

I think I must be misusing something but I cannot understand what I am doing wrong, I hope you will spot it right away!

**Comment by rperon** [comment]
Hello @voieducode,
Did you try to reset your browser cache ?

I think that the hydration issue come from the server reading common.json from the local file system and the client reading it from the browser cache. 
When I work with new string I often disable the browser cache so that I always get right version of the translation files. 

But this also mean that you will get this issue in production. (For the same reason)
One way to fix it is to use query string in the init of the httpbackend I the entry remix files. I can make an example but it will be on Monday. 

I hope this helps !

**Comment by voieducode** [comment]
Hey @rperon, thank you, it did help! Clearing the browser images and files cache fixed the string loading issue.

I think I get where you are going with the fix you mention, so I am looking forward to seeing your example on Monday.

I still get a hydration error in the console with a different message, but it does not seem to have an ill effect so I will not go down that rabbit hole for now:

```
react-dom.development.js:86  Warning: Expected server HTML to contain a matching <script> in <head>.
    at script
    at ClientHintCheck (http://localhost:3000/build/root-7A2TC7D6.js:3839:3)
    at head
    at html
    at Document (http://localhost:3000/build/root-7A2TC7D6.js:4030:3)
    at App (http://localhost:3000/build/root-7A2TC7D6.js:4106:16)
    at SentryRoot
    at RemixRoute (http://localhost:3000/build/_shared/chunk-DJH2R4SJ.js:8801:3)
    at RenderedRoute (http://localhost:3000/build/_shared/chunk-DJH2R4SJ.js:3101:5)
    at RenderErrorBoundary (http://localhost:3000/build/_shared/chunk-DJH2R4SJ.js:3685:9)
    at DataRoutes (http://localhost:3000/build/_shared/chunk-DJH2R4SJ.js:3399:5)
    at Router (http://localhost:3000/build/_shared/chunk-DJH2R4SJ.js:3478:15)
    at RouterProvider (http://localhost:3000/build/_shared/chunk-DJH2R4SJ.js:3348:5)
    at RemixErrorBoundary (http://localhost:3000/build/_shared/chunk-DJH2R4SJ.js:8389:5)
    at RemixBrowser (http://localhost:3000/build/_shared/chunk-DJH2R4SJ.js:10643:40)
    at I18nextProvider (http://localhost:3000/build/_shared/chunk-W6R7WUGP.js:122:5)
printWarning @ react-dom.development.js:86
error @ react-dom.development.js:60
warnForInsertedHydratedElement @ react-dom.development.js:10499
didNotFindHydratableInstance @ react-dom.development.js:11458
warnNonhydratedInstance @ react-dom.development.js:12385
tryToClaimNextHydratableInstance @ react-dom.development.js:12534
updateHostComponent @ react-dom.development.js:19902
beginWork @ react-dom.development.js:21618
beginWork$1 @ react-dom.development.js:27426
performUnitOfWork @ react-dom.development.js:26557
workLoopConcurrent @ react-dom.development.js:26543
renderRootConcurrent @ react-dom.development.js:26505
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 16 more frames
Show less
react-dom.development.js:12507  Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.
    at throwOnHydrationMismatch (react-dom.development.js:12507:9)
[...]

```

**Comment by voieducode** [comment]
I did go into a different rabbit hole in the end, and found this interesting commit that implements cache busting for language files: https://github.com/element-hq/element-web/pull/8710/commits/878190ba279312ce906c20a3e9a1148fe06a399c

I have a temporary and crude solution that busts the cache as you mention:

```ts
let loadPath = `/locales/{{lng}}/{{ns}}.json`

if (ENV.MODE === 'development') {
	// Prevent locales caching in dev
	// TODO: think about how to handle this in production
	loadPath += `?${Date.now()}`
}

[...]

async function hydrate() {
	await i18next
		.use(initReactI18next) // Tell i18next to use the react-i18next plugin
		.use(LanguageDetector) // Setup a client-side language detector
		.use(HTTPBackend) // Setup your backend
		.init({
			...i18n, // spread the configuration
			// This function detects the namespaces your routes rendered while SSR use
			ns: getInitialNamespaces(),
			backend: { loadPath: loadPath },

[...]
```

Thanks again for the quick feedback, it forced me to think more about the tricky but useful aspects of caching!

I think it would be cool to implement a hash-based cache busting strategy in your example. I wonder if remix has some infra that can be leveraged to do this easily.

**Comment by rperon** [comment]
Hello @voieducode,

Sorry for the delay, in the following PR #6, I've disable for dev env the cache of the translation files. As on the frontend, we are using an httpbackend to request those translation, we can easily update the `cache-control` header.

For production env, you can use the `queryStringParams`, with a custom input to force your client to use the latest version and have those translation also cache in the client browser.

I also tried to have remix reload translation when we are updating them but I was not able to do so. You still have to refresh the page manually.

Tell me if this is good for you so that I can merge the PR and close the issue.

**Comment by voieducode** [comment]
Thanks @rperon, just tried it out and it works well!
